# Generated by Django 4.1.5 on 2023-01-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_option_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='quiz',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question'),
            preserve_default=False,
        ),
    ]
