# Generated by Django 4.1.5 on 2023-01-26 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_option_quiz_option_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='bool_answer',
            field=models.BooleanField(default=None, null=True, verbose_name='Answer if True/False Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='num_answer',
            field=models.IntegerField(default=None, null=True, verbose_name='Answer if Numerical Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='bool_answer',
            field=models.BooleanField(default=None, null=True, verbose_name='Answer if True/False Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='negative_marking',
            field=models.IntegerField(default=1, verbose_name='Negative Marking'),
        ),
        migrations.AddField(
            model_name='question',
            name='num_answer',
            field=models.IntegerField(default=None, null=True, verbose_name='Answer if Numerical Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='positive_marking',
            field=models.IntegerField(default=4, verbose_name='Positive Marking'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Single Correct Question', 'SCQ'), ('Multiple Correct Question', 'MCQ'), ('Numerical Question', 'NUM'), ('True or False Question', 'BOOL')], default='SCQ', max_length=50, verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_selections', to='quiz.option'),
        ),
    ]
