# Generated by Django 4.1.5 on 2023-01-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_answer_bool_answer_answer_num_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='num_answer',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Answer if Numerical Question'),
        ),
    ]
