# Generated by Django 4.1.5 on 2023-01-26 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_num_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='selected',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SCQ', 'Single Correct Question'), ('MCQ', 'Multiple Correct Question'), ('NUM', 'Numerical Question'), ('BOOL', 'True or False Question')], default='SCQ', max_length=50, verbose_name='Question Type'),
        ),
        migrations.CreateModel(
            name='SelectedOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='quiz.answer')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_selections', to='quiz.option')),
            ],
        ),
    ]
