# Generated by Django 4.1.5 on 2023-01-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_answer_selected_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectedoptions',
            options={'verbose_name': 'Selected Option', 'verbose_name_plural': 'Selected Options'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Quiz Password'),
        ),
    ]
